# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2awsjhvvsBnOT5O2KSXq1JRcAGOhSeI
"""

"""
Santa's Workshop Tour 2019 - Greedy construction + Simulated Annealing.
"""

from __future__ import annotations

import argparse
import math
import random
import time
from pathlib import Path

import numpy as np
import pandas as pd

N_DAYS = 100
MIN_OCC = 125
MAX_OCC = 300
N_CHOICES = 10


# ---------------------------------------------------------------------
# Cost functions (official competition formulas)
# ---------------------------------------------------------------------

def preference_cost_from_rank(rank: int, n: int) -> int:
    if rank == 0:
        return 0
    if rank == 1:
        return 50
    if rank == 2:
        return 50 + 9 * n
    if rank == 3:
        return 100 + 9 * n
    if rank == 4:
        return 200 + 9 * n
    if rank == 5:
        return 200 + 18 * n
    if rank == 6:
        return 300 + 18 * n
    if rank == 7:
        return 300 + 36 * n
    if rank == 8:
        return 400 + 36 * n
    if rank == 9:
        return 500 + 235 * n
    return 500 + 434 * n  # not in top 10


def accounting_term(n_d: float, n_next: float) -> float:
    return (n_d - 125.0) / 400.0 * n_d ** (0.5 + abs(n_d - n_next) / 50.0)


def accounting_cost(occupancy) -> float:
    total = 0.0
    for d in range(N_DAYS):
        n_next = occupancy[d + 1] if d + 1 < N_DAYS else occupancy[d]
        total += accounting_term(occupancy[d], n_next)
    return total


# ---------------------------------------------------------------------
# Greedy construction
# ---------------------------------------------------------------------

def greedy_construct(sizes, choices):
    n_families = len(sizes)
    occupancy = [0] * N_DAYS
    assignment = [-1] * n_families

    order = sorted(range(n_families), key=lambda i: -sizes[i])  # big families first

    for f in order:
        n = sizes[f]
        placed = False
        for day in choices[f]:
            d = day - 1
            if occupancy[d] + n <= MAX_OCC:
                assignment[f] = int(day)
                occupancy[d] += n
                placed = True
                break
        if not placed:
            d = min(range(N_DAYS), key=lambda x: occupancy[x])
            assignment[f] = d + 1
            occupancy[d] += n

    return assignment, occupancy


def repair_min_occupancy(assignment, occupancy, sizes, cost_table, day_rank):
    n_families = len(assignment)
    while True:
        under_days = [d for d in range(1, N_DAYS + 1) if occupancy[d - 1] < MIN_OCC]
        if not under_days:
            break

        target_d = min(under_days, key=lambda d: occupancy[d - 1])
        best_f, best_from, best_delta = None, None, None

        for f in range(n_families):
            from_d = assignment[f]
            if from_d == target_d:
                continue
            n = sizes[f]
            if occupancy[from_d - 1] - n < MIN_OCC:
                continue
            if occupancy[target_d - 1] + n > MAX_OCC:
                continue

            old_cost = cost_table[f][day_rank[f][from_d]]
            new_cost = cost_table[f][day_rank[f][target_d]]
            delta = new_cost - old_cost

            if best_delta is None or delta < best_delta:
                best_delta = delta
                best_f = f
                best_from = from_d

        if best_f is None:
            # Fallback if strict min_occ cannot be maintained on source
            for f in range(n_families):
                from_d = assignment[f]
                if from_d == target_d:
                    continue
                n = sizes[f]
                if occupancy[target_d - 1] + n > MAX_OCC:
                    continue
                old_cost = cost_table[f][day_rank[f][from_d]]
                new_cost = cost_table[f][day_rank[f][target_d]]
                delta = new_cost - old_cost
                if best_delta is None or delta < best_delta:
                    best_delta = delta
                    best_f = f
                    best_from = from_d
            if best_f is None:
                raise RuntimeError("Cannot repair minimum occupancy: no valid moves found.")

        n = sizes[best_f]
        assignment[best_f] = target_d
        occupancy[best_from - 1] -= n
        occupancy[target_d - 1] += n

    return assignment, occupancy


# ---------------------------------------------------------------------
# Simulated Annealing
# ---------------------------------------------------------------------

def build_occupancy(assign, sizes):
    occ = [0] * N_DAYS
    for f, day in enumerate(assign):
        occ[day - 1] += sizes[f]
    return occ


def simulated_annealing(
        assignment, occupancy, sizes, choices, cost_table, day_rank,
        iterations=2_000_000, t0=100.0, t_end=0.01, seed=0, random_move_prob=0.0,
):
    rng = random.Random(seed)
    n_families = len(assignment)
    occ = list(occupancy)
    assign = list(assignment)

    def true_cost(a, o):
        p = sum(cost_table[f][day_rank[f][a[f]]] for f in range(n_families))
        return p + accounting_cost(o)

    current_cost = true_cost(assign, occ)
    best_assign = assign.copy()
    best_cost = current_cost

    alpha = (t_end / t0) ** (1.0 / iterations)
    T = t0

    accepted = 0
    t_start = time.time()

    for it in range(iterations):
        f = rng.randrange(n_families)
        n = sizes[f]
        src_day = assign[f]
        src = src_day - 1

        tgt_day = choices[f][rng.randrange(N_CHOICES)]
        tgt = tgt_day - 1

        if tgt_day == src_day:
            T *= alpha
            continue
        if occ[tgt] + n > MAX_OCC or occ[src] - n < MIN_OCC:
            T *= alpha
            continue
        if occ[tgt] + n > MAX_OCC or occ[src] - n < MIN_OCC:
            T *= alpha
            continue

        pref_delta = cost_table[f][day_rank[f][tgt_day]] - cost_table[f][day_rank[f][src_day]]

        affected = {src, tgt}
        if src > 0:
            affected.add(src - 1)
        if tgt > 0:
            affected.add(tgt - 1)

        before = 0.0
        for d in affected:
            n_next = occ[d + 1] if d + 1 < N_DAYS else occ[d]
            before += accounting_term(occ[d], n_next)

        occ[src] -= n
        occ[tgt] += n

        after = 0.0
        for d in affected:
            n_next = occ[d + 1] if d + 1 < N_DAYS else occ[d]
            after += accounting_term(occ[d], n_next)

        delta = pref_delta + (after - before)

        if delta < 0 or rng.random() < math.exp(-delta / T):
            assign[f] = tgt_day
            current_cost += delta
            accepted += 1
            if current_cost < best_cost:
                best_cost = current_cost
                best_assign = assign.copy()
        else:
            occ[src] += n
            occ[tgt] -= n

        T *= alpha

        if (it + 1) % 500_000 == 0:
            current_cost = true_cost(assign, occ)
            elapsed = time.time() - t_start
            print(
                f"  iter {it + 1:>10,} | T={T:8.3f} | current={current_cost:12,.1f} "
                f"| best={best_cost:12,.1f} | accepted={accepted:,} | {elapsed:.1f}s"
            )

    best_occ = build_occupancy(best_assign, sizes)
    best_cost = true_cost(best_assign, best_occ)
    return best_assign, best_occ, best_cost


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path("family_data.csv"))
    parser.add_argument("--output", type=Path, default=Path("submission.csv"))
    parser.add_argument("--iterations", type=int, default=7_000_000)
    parser.add_argument("--t0", type=float, default=150.0)
    parser.add_argument("--t_end", type=float, default=0.3)
    parser.add_argument("--seed", type=int, default=0)
    args, _ = parser.parse_known_args()

    df = pd.read_csv(args.input)
    choice_cols = [f"choice_{i}" for i in range(N_CHOICES)]
    sizes = df["n_people"].astype(int).tolist()
    choices = df[choice_cols].astype(int).values.tolist()
    n_families = len(df)

    cost_table = [
        [preference_cost_from_rank(r, sizes[f]) for r in range(N_CHOICES + 1)]
        for f in range(n_families)
    ]
    day_rank = []
    for f in range(n_families):
        ranks = [N_CHOICES] * (N_DAYS + 1)
        for r, day in enumerate(choices[f]):
            ranks[day] = r
        day_rank.append(ranks)

    print("Step 1: greedy construction...")
    assignment, occupancy = greedy_construct(sizes, choices)
    p = sum(cost_table[f][day_rank[f][assignment[f]]] for f in range(n_families))
    a = accounting_cost(occupancy)
    print(f"  greedy (before repair): preference={p:,.0f} accounting={a:,.1f} total={p + a:,.1f}")

    print("Step 2: repairing days under minimum occupancy...")
    assignment, occupancy = repair_min_occupancy(assignment, occupancy, sizes, cost_table, day_rank)
    p = sum(cost_table[f][day_rank[f][assignment[f]]] for f in range(n_families))
    a = accounting_cost(occupancy)
    print(f"  feasible greedy: preference={p:,.0f} accounting={a:,.1f} total={p + a:,.1f}")

    print(f"Step 3: simulated annealing ({args.iterations:,} iterations)...")
    best_assign, best_occ, best_cost = simulated_annealing(
        assignment, occupancy, sizes, choices, cost_table, day_rank,
        iterations=args.iterations, t0=args.t0, t_end=args.t_end, seed=args.seed,
    )

    final_pref = sum(cost_table[f][day_rank[f][best_assign[f]]] for f in range(n_families))
    final_acc = accounting_cost(best_occ)
    final_total = final_pref + final_acc

    assert min(best_occ) >= MIN_OCC and max(best_occ) <= MAX_OCC, \
        "Occupancy constraint violated - invalid submission!"

    print("\n" + "=" * 50)
    print(f"FINAL preference cost : {final_pref:,.0f}")
    print(f"FINAL accounting cost : {final_acc:,.2f}")
    print(f"FINAL TOTAL PENALTY   : {final_total:,.2f}")
    print("=" * 50)

    out = pd.DataFrame({"family_id": df["family_id"], "assigned_day": best_assign})
    out.to_csv(args.output, index=False)
    print(f"Saved {args.output}")


if __name__ == "__main__":
    main()

from google.colab import drive
drive.mount('/content/drive')